.TH CLIENT 1 "September 2025" "Version 0.4.1" "User Commands"
.SH NAME
client \- a demo program using custom string and file utilities
.SH SYNOPSIS
.B client
.RI [ options ]
.SH DESCRIPTION
The
.B client
program demonstrates the usage of custom utility functions
provided by the libmyutils library. These functions include
basic string manipulation and file analysis (word count and
simple grep functionality).

The program prints test results for string functions and file
functions to the console.

.SH AUTHOR
Written by Muhammad Saad Sabir.
